apiVersion: v2
name: kafka
description: Apache Kafka for Simple Time Service
type: application
version: 1.0.0
appVersion: "3.5"
dependencies:
  - name: kafka
    version: "25.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    alias: kafka
