apiVersion: v2
name: otel-collector
description: Wrapper chart for open-telemetry/opentelemetry-collector
type: application
version: 1.0.0
appVersion: "0.90.0"
dependencies:
  - name: opentelemetry-collector
    version: 0.90.0
    repository: https://open-telemetry.github.io/helm-charts
    alias: otel-collector
