apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/karthikcloudtech/simple-time-service.git
    targetRevision: time-ip
    path: gitops/helm-charts/platform/argocd
    helm:
      valueFiles:
        - values.yaml
        # NOTE: Ingress configuration should be managed separately via gitops/argocd/ingress
        # This prevents circular dependencies
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # NOTE: This application manages ArgoCD itself (self-management)
  # Initial ArgoCD installation must be done via script/bootstrap first
  # After bootstrap, this application takes over management
