apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  # CRDs must be installed first (wave -2), followed by serviceaccounts (wave -1)
  # This cert-manager deployment happens at wave 1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/karthikcloudtech/simple-time-service.git
    targetRevision: app
    path: gitops/helm-charts/platform/cert-manager
    helm:
      valueFiles:
        - values.yaml
      # NOTE: CRDs are installed by cert-manager-crds app (wave -2)
      # ServiceAccount is created by serviceaccounts app (wave -1) with IAM role annotation
      # Cert-manager deployment happens at wave 1, CRDs and ServiceAccount are guaranteed to exist
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # Ignore differences in status fields (cert-manager updates these)
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /status
    - group: cert-manager.io
      kind: CertificateRequest
      jsonPointers:
        - /status

