apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  # Sync after ServiceAccounts are created
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/karthikcloudtech/simple-time-service.git
    targetRevision: time-ip
    path: gitops/helm-charts/platform/cert-manager
    helm:
      valueFiles:
        - values.yaml
      # CRDs will be installed automatically with installCRDs=true
      # ServiceAccount is created by Helm with IAM role annotation for Route53 DNS-01 challenge
      # Get role ARN: terraform -chdir=infra/environments/prod output -raw cert_manager_role_arn
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # Ignore differences in status fields (cert-manager updates these)
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /status
    - group: cert-manager.io
      kind: CertificateRequest
      jsonPointers:
        - /status

