apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  # Sync AFTER ServiceAccounts are created (serviceaccounts uses wave -1)
  # ServiceAccounts must be created first with IAM role annotations (IRSA)
  # This ensures cluster-autoscaler pod gets AWS credentials via STS AssumeRole
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/karthikcloudtech/simple-time-service.git
    targetRevision: fastapi
    path: gitops/helm-charts/platform/cluster-autoscaler
    helm:
      valueFiles:
        - values.yaml
      # NOTE: ServiceAccount with IAM role annotation is pre-created by serviceaccounts chart (sync-wave: -1)
      # Cluster Autoscaler is set to NOT create ServiceAccount (serviceAccount.create: false in values.yaml)
      # This ensures IRSA (IAM Roles for Service Accounts) works correctly
      # The pre-created ServiceAccount is in kube-system with name: cluster-autoscaler-aws-cluster-autoscaler
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

