apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 30.1.2
    helm:
      values: |
        global:
          imageRegistry: public.ecr.aws

        image:
          repository: bitnami/kafka
          tag: 3.8.0

        kraft:
          enabled: true

        zookeeper:
          enabled: false

        controller:
          replicaCount: 3
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: controller

        broker:
          replicaCount: 2
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: broker

        listeners:
          client:
            protocol: PLAINTEXT
          controller:
            protocol: PLAINTEXT

        interBrokerListenerName: PLAINTEXT
        allowPlaintextListener: true

        persistence:
          enabled: true
          storageClass: gp3-wait
          size: 5Gi
