apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 30.1.2
    helm:
      valueFiles: []
      values: |
        kraft:
          enabled: true

        zookeeper:
          enabled: false

        replicaCount: 1

        persistence:
          enabled: true
          storageClass: gp3
          size: 5Gi

        listeners:
          client:
            protocol: PLAINTEXT

        autoCreateTopicsEnable: false

  destination:
    server: https://kubernetes.default.svc
    namespace: kafka

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
