apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
  repoURL: https://charts.bitnami.com/bitnami
  chart: kafka
  targetRevision: 30.1.2
  helm:
    values: |
      image:
        registry: public.ecr.aws
        repository: bitnami/kafka
        tag: 3.7.0

      kraft:
        enabled: true

      zookeeper:
        enabled: false

      controller:
        replicaCount: 1

      broker:
        replicaCount: 1

      listeners:
        client:
          protocol: PLAINTEXT
        controller:
          protocol: PLAINTEXT

      interBrokerListenerName: PLAINTEXT
      allowPlaintextListener: true

      persistence:
        enabled: true
        storageClass: gp3
        size: 5Gi
