apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serviceaccounts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Sync before Helm charts
spec:
  project: default
  source:
    repoURL: https://github.com/karthikcloudtech/simple-time-service.git
    targetRevision: app
    path: gitops/helm-charts/platform/serviceaccounts
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system  # Base namespace, ServiceAccounts specify their own namespaces
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

