apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  {{- if .Values.storageClass.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}

provisioner: {{ .Values.storageClass.provisioner }}
volumeBindingMode: WaitForFirstConsumer

allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
      - us-east-1a
      - us-east-1b

parameters:
  {{- range $key, $value := .Values.storageClass.parameters }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
