apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-time-service-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/karthikcloudtech/simple-time-service.git
    # Prod watches main branch
    targetRevision: time-ip
    path: gitops/helm-charts/apps/simple-time-service
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-time-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
