apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.container.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.container.name }}
spec:
  replicas: {{ .Values.rollout.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
              name: http
              protocol: TCP
          env:
          {{- range .Values.container.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.container.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.container.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.container.readinessProbe | nindent 12 }}
  {{- if .Values.rollout.strategy.canary.enabled }}
  strategy:
    canary:
      steps:
      {{- range .Values.rollout.strategy.canary.steps }}
        - setWeight: {{ .setWeight }}
        {{- if .pause }}
          pause:
            duration: {{ .pause }}
        {{- end }}
      {{- end }}
      analysis:
        interval: {{ .Values.rollout.strategy.canary.analysis.interval }}
        threshold: {{ .Values.rollout.strategy.canary.analysis.threshold }}
        maxWeight: {{ .Values.rollout.strategy.canary.analysis.maxWeight }}
        startingWeight: {{ .Values.rollout.strategy.canary.analysis.startingWeight }}
      metrics:
      {{- range .Values.rollout.strategy.canary.metrics }}
        - name: {{ .name }}
          weightPercentage: {{ .weightPercentage }}
      {{- end }}
      canaryService: {{ .Values.container.name }}-canary
      stableService: {{ .Values.container.name }}-stable
      {{- if .Values.rollout.strategy.canary.trafficRouting.alb.enabled }}
      trafficRouting:
        alb:
          ingress: {{ .Values.container.name }}-ingress
          servicePort: {{ .Values.rollout.strategy.canary.trafficRouting.alb.servicePort }}
      {{- end }}
  {{- end }}
