apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy after storage-class (wave 0) is ready
spec:
  project: default
  source:
    repoURL: https://github.com/karthikcloudtech/simple-time-service.git
    targetRevision: app
    path: gitops/helm-charts/observability/elasticsearch
    helm:
      valueFiles:
        - values.yaml
      # NOTE: StorageClass 'gp3' must exist before this application syncs
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

