apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-certs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy certs before elasticsearch (wave 1)
spec:
  project: default
  source:
    repoURL: https://github.com/karthikcloudtech/simple-time-service.git
    targetRevision: develop
    path: gitops/helm-charts/observability/elasticsearch-certs
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
