apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Deploy after elasticsearch (wave 1) is ready
spec:
  project: default
  source:
    repoURL: https://github.com/karthikcloudtech/simple-time-service.git
    targetRevision: develop
    path: gitops/helm-charts/observability/fluent-bit
    helm:
      valueFiles:
        - values.yaml
      # NOTE: Elasticsearch must be installed before Fluent-bit syncs
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

