apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/karthikbm2k25/simple-time-service.git
    targetRevision: main
    path: gitops/helm-charts/observability/kibana
    helm:
      valueFiles:
        - values.yaml
      # NOTE: Elasticsearch must be installed and ready before Kibana syncs
      # Consider using sync waves or manual sync for Kibana
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

