apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # Deploy after elasticsearch & kibana (wave 2) are ready
spec:
  project: default
  source:
    repoURL: https://github.com/karthikcloudtech/simple-time-service.git
    targetRevision: app
    path: gitops/helm-charts/observability/logging-ingress
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

