apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # Deploy after prometheus-stack (wave 1) is ready
spec:
  project: default
  source:
    repoURL: https://github.com/karthikcloudtech/simple-time-service.git
    targetRevision: develop
    path: gitops/helm-charts/observability/monitoring-ingress
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

