apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Deploy after otel-collector-config (wave 1) is ready
spec:
  project: default
  source:
    repoURL: https://github.com/karthikcloudtech/simple-time-service.git
    targetRevision: develop
    path: gitops/helm-charts/observability/otel-collector
    helm:
      valueFiles:
        - values.yaml
      # NOTE: ConfigMap 'otel-collector-config' must exist before this application syncs
      # Create ConfigMap via separate GitOps application or manually
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

