apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-time-service
spec:
  template:
    spec:
      containers:
        - name: simple-time-service
          # CI should replace <SHORT_SHA> with the commit short SHA for this env.
          image: karthikbm2k25/simple-time-service:<SHORT_SHA>


