apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
# Zookeeper StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: {{ .Values.namespace }}
  labels:
    app: zookeeper
spec:
  serviceName: zookeeper
  replicas: {{ .Values.kafka.zookeeper.replicaCount }}
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.5.0
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: election
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "5"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "10"
        - name: ZOO_CFG_EXTRA
          value: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7070"
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
        volumeMounts:
        - name: zookeeper-storage
          mountPath: /var/lib/zookeeper/data
        - name: zookeeper-logs
          mountPath: /var/log/zookeeper
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.kafka.zookeeper.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.kafka.zookeeper.persistence.size }}
  - metadata:
      name: zookeeper-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.kafka.zookeeper.persistence.storageClass }}
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: {{ .Values.namespace }}
  labels:
    app: zookeeper
spec:
  clusterIP: None
  selector:
    app: zookeeper
  ports:
  - port: 2181
    targetPort: 2181
    name: client
  - port: 2888
    targetPort: 2888
    name: server
  - port: 3888
    targetPort: 3888
    name: election
---
# Kafka StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
  labels:
    app: kafka
spec:
  serviceName: kafka
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.5.0
        ports:
        - containerPort: {{ .Values.kafka.service.port }}
          name: kafka
        env:
        - name: KAFKA_BROKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.ordinal
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-$(KAFKA_BROKER_ID).kafka.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.kafka.service.port }}
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "{{ .Values.kafka.config.logRetentionHours }}"
        - name: KAFKA_NUM_PARTITIONS
          value: "{{ .Values.kafka.config.numPartitions }}"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "{{ .Values.kafka.config.defaultReplicationFactor }}"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "{{ .Values.kafka.config.autoCreateTopicsEnable }}"
        resources:
          requests:
            memory: {{ .Values.kafka.resources.requests.memory }}
            cpu: {{ .Values.kafka.resources.requests.cpu }}
          limits:
            memory: {{ .Values.kafka.resources.limits.memory }}
            cpu: {{ .Values.kafka.resources.limits.cpu }}
        volumeMounts:
        - name: kafka-storage
          mountPath: /var/lib/kafka/data
        livenessProbe:
          tcpSocket:
            port: {{ .Values.kafka.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: {{ .Values.kafka.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: kafka-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.kafka.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.kafka.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
  labels:
    app: kafka
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
  - port: {{ .Values.kafka.service.port }}
    targetPort: {{ .Values.kafka.service.port }}
    name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  selector:
    app: kafka
  ports:
  - port: {{ .Values.kafka.service.port }}
    targetPort: {{ .Values.kafka.service.port }}
    name: kafka
