apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    # NOTE: Verify latest version at https://artifacthub.io/packages/helm/argo/argo-cd
    # Run: helm search repo argo/argo-cd --versions | head -1
    # Check ArgoCD version compatibility: https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/
    # This is for self-management - ArgoCD manages itself via GitOps
    # UPDATED: Using latest version - verify before deploying
    targetRevision: 8.0.0
    helm:
      parameters:
        - name: server.service.type
          value: ClusterIP
        - name: server.ingress.enabled
          value: "false"
        # NOTE: Ingress configuration should be managed separately via gitops/argocd/ingress
        # This prevents circular dependencies
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # NOTE: This application manages ArgoCD itself (self-management)
  # Initial ArgoCD installation must be done via script/bootstrap first
  # After bootstrap, this application takes over management
