apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    # NOTE: Verify latest version at https://artifacthub.io/packages/helm/cert-manager/cert-manager
    # Run: helm search repo jetstack/cert-manager --versions | head -1
    # Check Kubernetes version compatibility: https://cert-manager.io/docs/installation/supported-releases/
    # UPDATED: Using latest version - verify before deploying
    targetRevision: v1.15.0
    helm:
      parameters:
        - name: installCRDs
          value: "true"
      # CRDs will be installed automatically with installCRDs=true
      # ServiceAccount is created separately via gitops/serviceaccounts
      # Get role ARN: terraform -chdir=infra/environments/prod output -raw cert_manager_role_arn
      # Update gitops/serviceaccounts/cert-manager-sa.yaml with the role ARN
      # This annotation enables Route53 DNS-01 challenge for Let's Encrypt certificates
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # Sync after ServiceAccounts are created
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  # Ignore differences in status fields (cert-manager updates these)
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /status
    - group: cert-manager.io
      kind: CertificateRequest
      jsonPointers:
        - /status

