apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simple-time-service
  labels:
    app: simple-time-service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: simple-time-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s

