{{- if .Values.analysisTemplates.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Values.analysisTemplates.metrics5xx.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  metrics:
  - name: canary-5xx-rate
    interval: {{ .Values.analysisTemplates.metrics5xx.interval }}
    failureLimit: 1
    count: {{ .Values.analysisTemplates.metrics5xx.count }}
    successCondition: result < 2
    failureCondition: result >= 10
    provider:
      prometheus:
        address: http://prometheus.monitoring:9090
        query: |
          (
            sum(rate(http_requests_total{status=~"5..",namespace="{{ .Values.namespace.name }}"}[2m]))
            /
            sum(rate(http_requests_total{namespace="{{ .Values.namespace.name }}"}[2m]))
          ) * 100
  - name: canary-5xx-percentage-difference
    interval: {{ .Values.analysisTemplates.metrics5xx.interval }}
    failureLimit: 1
    count: {{ .Values.analysisTemplates.metrics5xx.count }}
    successCondition: result <= 2
    failureCondition: result > 5
    provider:
      prometheus:
        address: http://prometheus.monitoring:9090
        query: |
          (
            (sum(rate(http_requests_total{status=~"5..",version="canary",namespace="{{ .Values.namespace.name }}"}[2m]))
            /
            sum(rate(http_requests_total{version="canary",namespace="{{ .Values.namespace.name }}"}[2m]))
            * 100)
            -
            (sum(rate(http_requests_total{status=~"5..",version="stable",namespace="{{ .Values.namespace.name }}"}[2m]))
            /
            sum(rate(http_requests_total{version="stable",namespace="{{ .Values.namespace.name }}"}[2m]))
            * 100)
          )
{{- end }}
