apiVersion: v2
name: elasticsearch
description: Wrapper chart for elastic/elasticsearch
type: application
version: 1.0.0
appVersion: "8.5.1"
dependencies:
  - name: elasticsearch
    version: 8.5.1
    repository: https://helm.elastic.co
    alias: elasticsearch
