apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    # NOTE: Replace ACCOUNT_ID with your AWS account ID
    # Get role ARN: terraform -chdir=infra/environments/prod output -raw aws_load_balancer_controller_role_arn
    eks.amazonaws.com/role-arn: "arn:aws:iam::017019814021:role/simple-time-service-aws-load-balancer-controller-role"

