apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    # NOTE: Replace ACCOUNT_ID with your AWS account ID
    # Get role ARN: terraform -chdir=infra/environments/prod output -raw cert_manager_role_arn
    eks.amazonaws.com/role-arn: "arn:aws:iam::017019814021:role/simple-time-service-cert-manager-role"

